#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="${1:-}"

if [[ -z "${WORKSPACE_ROOT}" ]]; then
  echo "Usage: create-demo-workspace.sh <target-dir>" >&2
  exit 1
fi

mkdir -p "${WORKSPACE_ROOT}"
WORKSPACE_ROOT="$(cd "${WORKSPACE_ROOT}" && pwd)"

WEB_DIR="${WORKSPACE_ROOT}/demo-web"
API_DIR="${WORKSPACE_ROOT}/demo-api"

mkdir -p "${WEB_DIR}" "${API_DIR}"
git -C "${WEB_DIR}" init -q
git -C "${API_DIR}" init -q

cat > "${WEB_DIR}/package.json" <<'EOF'
{
  "name": "demo-web",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "serve": "python3 -m http.server 38080"
  }
}
EOF

cat > "${WEB_DIR}/index.html" <<'EOF'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>OmniContext Demo</title>
    <style>
      body { font-family: ui-sans-serif, system-ui; margin: 40px; line-height: 1.5; }
      .card { max-width: 720px; padding: 24px; border: 1px solid #ddd; border-radius: 16px; }
      .cta { display: inline-block; margin-top: 16px; padding: 10px 16px; background: #111; color: #fff; border-radius: 999px; text-decoration: none; }
    </style>
  </head>
  <body>
    <div class="card">
      <h1>OmniContext Demo</h1>
      <p>This page is used for browser smoke evidence collection.</p>
      <a class="cta" href="#ready">Ready</a>
    </div>
  </body>
</html>
EOF

cat > "${API_DIR}/go.mod" <<'EOF'
module demo-api

go 1.22
EOF

cat > "${WORKSPACE_ROOT}/README.md" <<'EOF'
# OmniContext Demo Workspace

## Quick Start

1. Start the demo web app:
   `cd demo-web && python3 -m http.server 38080`
2. In another shell, run:
   `../omni-context-skill/scripts/omni-context status .`
3. Collect browser evidence:
   `../omni-context-skill/scripts/omni-context collect-test-evidence . demo-web homepage-smoke --platform web`
EOF

"${SCRIPT_DIR}/omni-context" init "${WORKSPACE_ROOT}" >/dev/null
"${SCRIPT_DIR}/omni-context" init-project-standards "${WORKSPACE_ROOT}" demo-web webapp >/dev/null
"${SCRIPT_DIR}/omni-context" init-project-standards "${WORKSPACE_ROOT}" demo-api backend-service >/dev/null
"${SCRIPT_DIR}/omni-context" rules-pack-init "${WORKSPACE_ROOT}" demo-web default-balanced >/dev/null
"${SCRIPT_DIR}/omni-context" rules-pack-init "${WORKSPACE_ROOT}" demo-api backend-stability >/dev/null
"${SCRIPT_DIR}/omni-context" start-workflow "${WORKSPACE_ROOT}" demo-web "Homepage Smoke" demo >/dev/null
"${SCRIPT_DIR}/omni-context" start-workflow "${WORKSPACE_ROOT}" demo-api "API Health" api-demo >/dev/null
"${SCRIPT_DIR}/omni-context" init-test-suite "${WORKSPACE_ROOT}" demo-web "Homepage Smoke" homepage-smoke >/dev/null
"${SCRIPT_DIR}/omni-context" init-test-suite "${WORKSPACE_ROOT}" demo-api "API Health" health-check >/dev/null

python3 - "${WORKSPACE_ROOT}" <<'PY'
import sys
from pathlib import Path
root = Path(sys.argv[1])
runtime = root / ".omnicontext/projects/demo-web/standards/runtime.toml"
text = runtime.read_text().replace("http://localhost:3000", "http://127.0.0.1:38080")
runtime.write_text(text)

suite = root / ".omnicontext/projects/demo-web/tests/suites/homepage-smoke.md"
suite.write_text(
"""# Homepage Smoke

- suite_id: homepage-smoke
- source_status: confirmed
- platform: web
- execution_target: homepage
- interaction_requirement: real-user-click

## Required Cases

- [required] Open the homepage

## Optional Cases

- [optional] Observe the rendered call-to-action

## Preconditions

- demo web server is running on port 38080

## Steps

- [step] goto: /
- [step] wait_for: text=OmniContext Demo
- [step] click: text=Ready
- [step] assert_text: text=Ready
- [step] screenshot: final-state

## Notes

- generated by create-demo-workspace.sh
"""
)

api_suite = root / ".omnicontext/projects/demo-api/tests/suites/health-check.md"
api_suite.write_text(
"""# Health Check

- suite_id: health-check
- source_status: confirmed
- platform: backend
- execution_target: api-health
- interaction_requirement: service-request

## Required Cases

- [required] GET / returns HTTP 200

## Optional Cases

- [optional] Response body includes the word demo

## Preconditions

- demo api server is running on port 8080

## Steps

- [step] request: GET /
- [step] expect_status: 200

## Notes

- generated by create-demo-workspace.sh
"""
)
PY

echo "Created demo workspace at ${WORKSPACE_ROOT}"
echo "Projects:"
echo "- demo-web"
echo "- demo-api"
echo "Next:"
echo "- cd ${WEB_DIR} && python3 -m http.server 38080"
echo "- ${SCRIPT_DIR}/omni-context collect-test-evidence ${WORKSPACE_ROOT} demo-web homepage-smoke --platform web"
